GET http://localhost:3000/index

###

GET http://localhost:3000/index/cccccccccccc

###

POST http://localhost:3000/index
Content-Type: application/json

{
    "body": "It has an oaky afterbirth",
    "author": "Michael Scott"
}

###

DELETE http://localhost:3000/index/645e4b5f69f33639c3b859bd

###

PATCH http://localhost:3000/index/645ba2f3eb235a7afc00f21a
Content-Type: application/json

{
    "body": "That's what she said"
}

### 

PUT http://localhost:3000/index/645ba2f3eb235a7afc00f21a
Content-Type: application/json

{
    "body": "I am not superstitious, I am just a little bit stitious",
    "author": "Michael Scott"
}
###


POST http://localhost:3000/login
Content-Type: application/json

{
    "password": "cats",
    "username": "Edith"
}

###

GET http://localhost:3000/logout